language: node_js
node_js:
  - "10"


cache:
  directories:
    - "node_modules"
    
notifications:
  slack: cse112-sp19-team4:Ni7i8GfaOAv6L7mitfqEkRcn

addons:
  code_climate:
    repo_token: 3c07ee7e30821cfc4ed2312c05e18ed35f1fe3f3465fcc9ccd0569db8a68dd8d

script: istanbul cover node_modules/mocha/bin/_mocha -- -R spec

before_script: 
  - npm install codeclimate-test-reporter istanbul -g
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
install:
  - npm install  

