language: node_js
node_js:
  - "10"

notifications:
  slack: cse112-sp19-team4:Ni7i8GfaOAv6L7mitfqEkRcn

cache:
  directories:
    - node_modules
    - bower_components

install:
  - npm install  
  - npm run run-install

script:
  - npm run test
  
addons:
  sauce_connect: true